### ISSUE TITLE
Add social logins

### ISSUE THREAD

**Issue by heitortsergent** [devorganizers/speakerthumbs#16]
https://orchestrate.io/blog/2014/06/26/build-user-authentication-with-node-js-express-passport-and-orchestrate/

**Comment by jneto** [comment]
I made it for facebook. Tomorrow I am going to made it to the others social logins.

**Comment by heitortsergent** [comment]
:+1:. Do you wanna create a new branch for it, and then make a pull request to master?

**Comment by jneto** [comment]
I already made a push.
